<div class="wrap">
    <h1><a href="//speedm.qq.com/main.shtml" onclick="PTTSendClick('logo','speed','QQ飞车手游SPEDD');" title="QQ飞车手游官网">QQ飞车手游SPEDD</a></h1>
    <ul>
        <li class="on" ><a href="//speedm.qq.com/act/a20170627yuyue/" onclick="PTTSendClick('btn','order','立即预约');" title="立即预约">立即预约</a></li>
        <li><a href="" onclick="PTTSendClick('btn','guessing','竞猜大咖');" title="大咖竞猜">竞猜大咖</a></li>
        <li><a href="" onclick="PTTSendClick('btn','demystify','揭秘大咖');" title="揭秘大咖">揭秘大咖</a></li>
        <li><a href="" onclick="PTTSendClick('btn','welfare','敬请期待');" title="福利派送">敬请期待</a></li>
    </ul>
    <h2 class="black">QQ飞车手游携手张杰一起搞事情</h2>
</div>
